#!/usr/bin/env python3
"""
Claude Capabilities Demo - Preview Version (Non-Interactive)
Shows all content without requiring user input
"""

import os
import sys
from datetime import datetime
import time

class ClaudeDemo:
    def __init__(self):
        self.demos_completed = []
        self.start_time = datetime.now()

    def print_separator(self):
        print("\n" + "─" * 70 + "\n")

    def print_header(self, title):
        print("\n" + "="*60)
        print(f"  {title}")
        print("="*60 + "\n")

    def print_subheader(self, text):
        print(f"\n--- {text} ---\n")

    def welcome(self):
        self.print_header("CLAUDE CAPABILITIES DEMONSTRATION")
        print("This demo was WRITTEN BY CLAUDE to showcase what AI can do.")
        print("Yes, Claude wrote this entire program you're running right now.")
        print("\nWhat you'll see:")
        print("  1. Code Generation (you're experiencing it!)")
        print("  2. Complex Problem Solving")
        print("  3. Pattern Recognition & Analysis")
        print("  4. Natural Language Understanding")
        print("  5. Data Processing & Visualization")
        print("  6. Logic & Reasoning")
        self.print_separator()

    def demo_1_meta(self):
        self.print_header("Demo 1: Code Generation (META)")

        print("Here's something wild: This program was generated by Claude in seconds.")
        print("\nClaude can:")
        print("  - Write complete, working programs in any language")
        print("  - Debug existing code")
        print("  - Explain code line-by-line")
        print("  - Convert between programming languages")
        print("  - Optimize and refactor code")

        print("\n🤯 MIND-BENDER: An AI wrote the code that's telling you about AI")

        self.demos_completed.append("Code Generation")
        self.print_separator()

    def demo_2_problem_solving(self):
        self.print_header("Demo 2: Problem Solving & Logic")

        print("Let's solve a classic logic puzzle together.\n")
        print("THE BRIDGE CROSSING PROBLEM:")
        print("-" * 50)
        print("Four people need to cross a bridge at night.")
        print("They have one flashlight and the bridge holds max 2 people.")
        print("Each person walks at a different speed:")
        print("  - Person A: 1 minute")
        print("  - Person B: 2 minutes")
        print("  - Person C: 5 minutes")
        print("  - Person D: 10 minutes")
        print("\nWhen two cross together, they go at the slower person's pace.")
        print("What's the FASTEST time to get everyone across?")

        print("\n" + "="*50)
        print("CLAUDE'S SOLUTION:")
        print("="*50)
        print("\nOptimal strategy (17 minutes total):")
        print("  1. A and B cross together → 2 min (total: 2)")
        print("  2. A returns alone → 1 min (total: 3)")
        print("  3. C and D cross together → 10 min (total: 13)")
        print("  4. B returns alone → 2 min (total: 15)")
        print("  5. A and B cross together → 2 min (total: 17)")

        print("\nWHY THIS IS IMPRESSIVE:")
        print("  ✓ Claude reasoned through multiple possibilities")
        print("  ✓ Found the optimal solution (not just 'a' solution)")
        print("  ✓ Explained the logic step-by-step")

        print("\nThis same reasoning applies to:")
        print("  - Business optimization problems")
        print("  - Resource allocation")
        print("  - Strategic planning")
        print("  - Debugging complex issues")

        self.demos_completed.append("Problem Solving")
        self.print_separator()

    def demo_3_pattern_recognition(self):
        self.print_header("Demo 3: Pattern Recognition & Analysis")

        sequences = [
            ("1, 1, 2, 3, 5, 8, 13, ?", "21 (Fibonacci sequence)"),
            ("2, 6, 12, 20, 30, ?", "42 (n × (n+1))"),
            ("J, F, M, A, M, J, ?", "J (Months: July)"),
            ("1, 4, 9, 16, 25, ?", "36 (Perfect squares)"),
        ]

        print("Claude excels at finding patterns. Here are some examples:\n")

        for i, (seq, answer) in enumerate(sequences, 1):
            print(f"{i}. {seq}")
            print(f"   Answer: {answer}\n")

        self.print_subheader("Real-World Applications")
        print("This pattern recognition helps with:")
        print("  - Analyzing business trends")
        print("  - Spotting anomalies in data")
        print("  - Understanding code patterns")
        print("  - Predicting outcomes")
        print("  - Finding bugs (unusual patterns in behavior)")

        self.demos_completed.append("Pattern Recognition")
        self.print_separator()

    def demo_4_text_analysis(self):
        self.print_header("Demo 4: Natural Language Understanding")

        print("Claude doesn't just match keywords—it understands MEANING.\n")

        ambiguous_sentences = [
            ("I saw the man with the telescope",
             "Who has the telescope? Ambiguous! Could be:\n     - I used a telescope to see the man\n     - I saw a man who was holding a telescope"),

            ("The chicken is ready to eat",
             "Who's eating? Ambiguous!\n     - The chicken is cooked and ready to be eaten\n     - The chicken (animal) is hungry and ready to eat"),

            ("Time flies like an arrow",
             "Multiple interpretations:\n     - Time passes quickly (metaphor)\n     - Measure the speed of flies like you'd measure an arrow\n     - A species of flies called 'time flies' enjoys arrows"),
        ]

        for sentence, explanation in ambiguous_sentences:
            print(f'"{sentence}"')
            print(f"  → {explanation}\n")

        self.print_subheader("Why This Matters")
        print("Claude can:")
        print("  ✓ Understand context and nuance")
        print("  ✓ Detect sarcasm and tone")
        print("  ✓ Disambiguate based on context")
        print("  ✓ Summarize complex documents")
        print("  ✓ Extract key information from contracts/legal docs")
        print("  ✓ Translate between languages (with context)")

        self.demos_completed.append("Language Understanding")
        self.print_separator()

    def demo_5_data_processing(self):
        self.print_header("Demo 5: Data Processing & Calculation")

        print("Let's process some data in real-time.\n")

        # Generate some sample data
        sample_data = [
            {"name": "Project Alpha", "cost": 150000, "roi": 2.3, "duration": 8},
            {"name": "Project Beta", "cost": 80000, "roi": 3.1, "duration": 5},
            {"name": "Project Gamma", "cost": 220000, "roi": 1.8, "duration": 12},
            {"name": "Project Delta", "cost": 95000, "roi": 2.7, "duration": 6},
        ]

        print("Sample Project Data:")
        print("-" * 70)
        for p in sample_data:
            print(f"{p['name']:15} | Cost: ${p['cost']:>7,} | ROI: {p['roi']}x | Duration: {p['duration']} months")

        print("\n" + "="*70)
        print("ANALYSIS:")
        print("="*70)

        # Calculations
        total_cost = sum(p['cost'] for p in sample_data)
        avg_roi = sum(p['roi'] for p in sample_data) / len(sample_data)
        best_roi = max(sample_data, key=lambda x: x['roi'])
        fastest = min(sample_data, key=lambda x: x['duration'])

        print(f"\nTotal Investment: ${total_cost:,}")
        print(f"Average ROI: {avg_roi:.2f}x")
        print(f"Best ROI: {best_roi['name']} ({best_roi['roi']}x)")
        print(f"Fastest Project: {fastest['name']} ({fastest['duration']} months)")

        # Recommendation engine
        print("\n" + "-"*70)
        print("RECOMMENDATION ENGINE:")
        print("-"*70)

        efficiency_scores = []
        for p in sample_data:
            score = (p['roi'] * 10) / (p['duration'] * 0.5) - (p['cost'] / 100000)
            efficiency_scores.append((p['name'], score))

        efficiency_scores.sort(key=lambda x: x[1], reverse=True)

        print("\nProjects ranked by efficiency (ROI vs time vs cost):")
        for i, (name, score) in enumerate(efficiency_scores, 1):
            print(f"  {i}. {name} (score: {score:.2f})")

        print("\n💡 This kind of analysis can be done on:")
        print("  - Financial data")
        print("  - Customer information")
        print("  - Sales figures")
        print("  - Inventory management")
        print("  - Any spreadsheet or database")

        self.demos_completed.append("Data Processing")
        self.print_separator()

    def demo_6_reasoning(self):
        self.print_header("Demo 6: Multi-Step Reasoning")

        print("Claude can chain together multiple reasoning steps.\n")
        print("SCENARIO: You're planning a cross-country road trip")
        print("-" * 60)

        print("\nGiven information:")
        print("  - Distance: 2,800 miles")
        print("  - Car gets 28 MPG")
        print("  - Gas costs $3.50/gallon")
        print("  - You drive 8 hours/day at average 60 mph")
        print("  - Hotels cost $120/night")
        print("  - You eat 3 meals/day at $15/meal")

        print("\n" + "="*60)
        print("STEP-BY-STEP REASONING:")
        print("="*60)

        print("\nStep 1: Calculate driving time")
        print("  2,800 miles ÷ 60 mph = 46.67 hours")
        print("  46.67 hours ÷ 8 hours/day = 5.83 days")
        print("  Round up to 6 days of driving")

        print("\nStep 2: Calculate gas costs")
        print("  2,800 miles ÷ 28 MPG = 100 gallons needed")
        print("  100 gallons × $3.50 = $350")

        print("\nStep 3: Calculate hotel costs")
        print("  6 nights × $120 = $720")

        print("\nStep 4: Calculate food costs")
        print("  6 days × 3 meals × $15 = $270")

        print("\nStep 5: Total cost")
        print("  Gas ($350) + Hotels ($720) + Food ($270) = $1,340")

        print("\n" + "="*60)
        print(f"TOTAL TRIP COST: $1,340")
        print("="*60)

        print("\n🧠 This demonstrates:")
        print("  ✓ Breaking complex problems into steps")
        print("  ✓ Remembering intermediate results")
        print("  ✓ Combining multiple calculations")
        print("  ✓ Practical real-world problem solving")

        self.demos_completed.append("Multi-Step Reasoning")
        self.print_separator()

    def final_summary(self):
        self.print_header("DEMO COMPLETE - WHAT YOU JUST EXPERIENCED")

        elapsed = datetime.now() - self.start_time
        seconds = int(elapsed.total_seconds())

        print(f"In the last {seconds} seconds, you experienced:\n")

        for i, demo in enumerate(self.demos_completed, 1):
            print(f"  ✓ {demo}")

        self.print_subheader("But Wait, There's More!")

        print("This demo only scratched the surface. Claude can also:")
        print("  • Read and analyze images (photos, diagrams, charts)")
        print("  • Process PDFs and extract information")
        print("  • Write in any style (formal, casual, technical)")
        print("  • Debug and optimize code")
        print("  • Research topics and summarize findings")
        print("  • Help with creative writing")
        print("  • Tutor on any subject")
        print("  • Analyze legal or financial documents")
        print("  • Plan projects and break down complex tasks")
        print("  • And much more...")

        self.print_subheader("The Key Difference")

        print("Most AI chatbots: Simple question → Simple answer")
        print("Claude: Complex problem → Reasoned solution with explanation")

        print("\nIt's not about replacing human thinking.")
        print("It's about ENHANCING what humans can do.")

        self.print_subheader("Context Window: The Secret Weapon")

        print("Claude can hold ~150,000 words in memory at once.")
        print("That's like reading 3-4 entire novels simultaneously")
        print("and being able to answer questions about all of them.")

        print("\nThis means Claude can:")
        print("  • Analyze entire codebases")
        print("  • Read full legal contracts")
        print("  • Process complete research papers")
        print("  • Review whole business proposals")
        print("  • Keep track of long, complex conversations")

        print("\n" + "="*60)
        print("  Thanks for exploring what AI can do!")
        print("  Questions? Just ask Claude. 😉")
        print("="*60 + "\n")

    def run(self):
        self.welcome()
        self.demo_1_meta()
        self.demo_2_problem_solving()
        self.demo_3_pattern_recognition()
        self.demo_4_text_analysis()
        self.demo_5_data_processing()
        self.demo_6_reasoning()
        self.final_summary()

if __name__ == "__main__":
    demo = ClaudeDemo()
    demo.run()
